name: Generate Sprites

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install generator
        run: cargo install spreet
      - name: Generate sprites
        run: |
          spreet svg seamarks-sprites
          spreet --retina svg seamarks-sprites@2
      - name: Check difference
        run: |
          git add --all . && \
          status=$(git status -s .) && \
          echo $status && \
          echo "GIT_STATUS=${status//$'\n'/\\n}" >> $GITHUB_ENV
      - name: Push changes
        if: "contains(env.GIT_STATUS, 'sprites')"
        run: |
          git add --all . && \
          git config --global user.email "action@github.com" && \
          git config --global user.name "Github CI" && \
          git commit -a -m "generate sprite sheets" && \
          git push